[package]
# name of library for Java
name = "rust_java_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19.0"
primitive-types = "0.10.1"

[lib]
crate_type = ["cdylib"]