/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainClass */

#ifndef _Included_MainClass
#define _Included_MainClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainClass
 * Method:    bigAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MainClass_bigAdd
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
